version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - apt-get update
      - apt-get install -y default-mysql-client
      - pip install -r "$CODEBUILD_SRC_DIR/requirements.txt"

  pre_build:
    commands:
      - export EXTERNAL_FIXTURES_DIR="$CODEBUILD_SRC_DIR/db/fixtures"
      - echo "Using EXTERNAL_FIXTURES_DIR=$EXTERNAL_FIXTURES_DIR"

  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR_SECONDARY"

      - for sql in $(ls sql/*.sql | sort); do
          echo "Applying $sql";
          mysql -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE < $sql;
        done

      - cd "$CODEBUILD_SRC_DIR_SECONDARY/src"

      - python manage.py migrate

      - python manage.py load_fixtures --dir "$CODEBUILD_SRC_DIR_SECONDARY/src"

      - python manage.py load_fixtures --dir "$CODEBUILD_SRC_DIR/db" --glob "fixtures/*.json"
